// Custom colors
pragma Singleton
import QtQuick 2.5

/*
    The QtObject type is a non-visual element which contains only the objectName property.
    Useful to create a QtObject if you need an extremely lightweight type to enclose a set
    of custom properties
 */
QtObject {

    readonly property color black:              "#000000"
    readonly property color red:                "#ff0000"
    readonly property color dark_red:           "#630000"
    readonly property color really_dark_red:	"#1c0000"
    readonly property color transparent:		"#00000000"
    readonly property color transp_black:		"#a0000000"
    readonly property color sea_green:          "#00a097"
    readonly property color dark_blue:          "#001a3e"
    readonly property color light_sea_green:	"#a1ede8"
    readonly property color light_sea_green_transp:		"#1aa1ede8"
    readonly property color light_blue:         "#5fb8e5"
    readonly property color dark_blue_2:		"#0b2957"
    readonly property color blue:               "#B3D9FF"
    readonly property color sc_signal1:         "#F5F58E"
    readonly property color sc_signal1_transp:	"#3AF5F58E"
    readonly property color sc_signal1_blur:	"#8AF5F58E"
    readonly property color sc_signal1_log:		"#ffffff"
    readonly property color sc_signal2:         "#8ECCF5"
    readonly property color sc_signal2_transp:	"#3A8ECCF5"
    readonly property color sc_signal2_blur:	"#8A8ECCF5"
    readonly property color sc_signal2_log:		"#ff0055"
    readonly property color sc_signal3:         "#21DE9C"
    readonly property color sc_signal3_transp:	"#3A21DE9C"
    readonly property color sc_signal3_blur:	"#8A21DE9C"
    readonly property color sc_signal3_log:		"#99FF00"
    readonly property color tram_line_color:	"#A0F2B541"
    readonly property color tram_rect_color:	"#40F2B541"
    readonly property color anchor_tile:		"#f7f7d5"
    readonly property color phase_arc:          "#91DCF2"
    readonly property color bottle_green:		"#00784f"
    readonly property color dark_green:         "#03261f"
    readonly property color light_green:		"#c0e2d1"
    readonly property color dirty_green:		"#3E4A19"
    readonly property color parrot_green:		"#d8ff3f"
    readonly property color white:              "#ffffff"
    readonly property color light_olive:		"#5a6f1b"
    readonly property color med_olive:          "#6b7b25"
    readonly property color dark_olive:         "#313918"
    readonly property color royal_blue:         "#1147b2"
    readonly property color orange:             "#e5481e"
    readonly property color reddish_black:		"#1a1a1a"
    readonly property color salmon:             "#ff543e"
    readonly property color teal:               "#037fa1"
    readonly property color teal_transp:		"#80037fa1"
    readonly property color teal_gray:          "#e6eded"
    readonly property color light_teal:         "#69D7F5"
    readonly property color tealish_black:		"#030b0d"
    readonly property color burlap:             "#edd3bc"
    readonly property color burlap_disabled:	"#70edd3bc"
    readonly property color info_bubble_border:	"#575858"
    readonly property color button_shadow:		"#2c2e2e"
    readonly property color button_bgnd:		"#134552"
    readonly property color button_disabled:	"#424C4F"
    readonly property color button_pressed_bgnd:"#196478"
    readonly property color button_on_bgnd:     thr_box_color;
    readonly property color thr_box_color:		"#F2A533"
    readonly property color thr_adj_color:		"#40F2A533"
    readonly property color thr_pressed_text:	"#40372B"
    readonly property color log_box_color:		"#FF0000"
    readonly property color log_pressed_text:	"#FFFFFF"
    readonly property color alarm_bgnd:         "#A00009"
    readonly property color alarm_signal_color:	"#FF0000"
    readonly property color dialog_gradient_start:		"#F5F2DA"
    readonly property color dialog_gradient_mid:"#D1CEA9"
    readonly property color dialog_gradient_end:"#DED7AB"
    readonly property color wheel_center:		"#1a5d6f"
    readonly property color wheel_offcenter:	"#030b0d"
    readonly property color title_color:		"#aeaeae"
    readonly property color ring_color:         "#6a7372"
    readonly property color phase_dialog_border_gray:   "#506a7372"
    readonly property color phase_dialog_border:"#30edd3bc"
    readonly property color phase_dialog_bgnd:	"#10191c"
    readonly property color list_divider:		"#2d2e2e"
    readonly property color sc_view_bgnd:		"#a0030b0d"
    readonly property color tile_static:		"#00757a"
    readonly property color tile_dynamic:		"#3d7fac"
    readonly property color tile_sigma:         "#00744d"
    readonly property color tile_thickness:		"#96b330"

    readonly property color toolbar_text:		"#aeaeae"
    readonly property color toolbar_bgnd:		"#222222"
    readonly property color toolbar_bgnd_pressed:		"#444"
    readonly property color toolbar_bgnd_top:	"#393939"
    readonly property color toolbar_bgnd_bot:	"#1b1b1b"

    readonly property color plot_label_color:	ring_color;

}
